language: haskell

ghc: # matrix that cover recent years
  - "7.4.2" # Jun 2012
  - "7.6.3" # Apr 2013
  - "7.8"   # Apr 2014
  - "7.10"  # Apr 2015
  - "8.0.1" # May 2016
  - "8.2.2" # Nov 2017
  - "8.4.1" # Mar 2018
